#!/usr/bin/env zsh

~/.setup/confgit.sh

case "$OSTYPE" in
  darwin*)
    if [[ ! -d "/usr/local/Homebrew" ]] && [[ -f "/private/etc/bashrc_Apple_Terminal" ]]; then
      # Install xcode cli components
      xcode-select --install
      # Install brew using checked-in copy of https://raw.githubusercontent.com/Homebrew/install/master/install
      /bin/bash -c ~/.setup/installbrew.sh

      brew doctor;
      brew update;

      # Install taps here
      brew tap git-chglog/git-chglog;
      # Tap fonts
      brew tap homebrew/cask-fonts
      # Gitlab kubelogin tap
      brew tap incubator/kubelogin https://gitlab.nordstrom.com/k8s/incubator/homebrew-kubelogin.git;
    fi

    # Install new brew packages
    brewtemp=$(mktemp /tmp/upbrew.XXXX)
    brew deps --installed | awk -F ':'  '{print $1}' > $brewtemp
    comm -13 $brewtemp ~/.setup/list.brew | while read -r b; do brew install $b ; done
    rm $brewtemp

    # Install new cask packages
    casktemp=$(mktemp /tmp/upbrewcask.XXXX)
    brew cask list -1 > $casktemp
    comm -13 $casktemp ~/.setup/list.brewcask | while read -r b; do brew cask install $b ; done
    rm $casktemp

    brew update;
    brew upgrade;
    brew cask upgrade;
    brew cleanup;

    # Update all package lists
    brew deps --installed | awk -F ':'  '{print $1}' > ~/.setup/list.brew
    brew cask list -1 > ~/.setup/list.brewcask
    # fetch the updated brew install script only if new
    curl -fsSL -z ~/.setup/installbrew.sh --output ~/.setup/installbrew.sh https://raw.githubusercontent.com/Homebrew/install/master/install.sh
    # Git config for work
    fd -H -t d -E mod -E vendor '.git$' ~/code/work -x bash -c "cd {//}; git config user.email tyler.m.davis@nordstrom.com; git config http.cookiefile /Users/tydavis/.gitcookies-work;" ;
  ;;
  linux*)
    # == ARCHLINUX ==
    sudo pacman -Syu;
    # Dump all packages into list
    echo "base" > ~/.setup/paclist
    echo "base-devel" >> ~/.setup/paclist
    pacman -Qqet | grep -v "$(pacman -Qqg base-devel)" | grep -v "$(pacman -Qqm)" >> ~/.setup/paclist
    # AUR installed / local-installed packages
    pacman -Qmq > ~/.setup/pacaur
    # Git config for work
    fd -H -t d -E mod -E vendor '.git$' ~/code/work -x bash -c "cd {//}; git config user.email tyler.m.davis@nordstrom.com; git config http.cookiefile /home/tydavis/.gitcookies-work;" ;
  ;;
esac

if [ "$(command -v fetchgit)" ]; then
  # Update all existing repos
  fd -H -t d -E mod -E vendor '.git$' ~/code -x bash -c "cd {//}; ~/.bin/fetchgit;" ;
  fd -H -t d '.git$' ~/.vim -x bash -c "cd {//}; ~/.bin/fetchgit;" ;
fi

if [ "$(command -v gcloud )" ]; then
  # Update Gcloud
  gcloud components update -q;
fi

if [ "$(command -v gitrect)" ]; then
  # Synchronize work repo updates
  gitrect -d ~/code/work -c ~/code/work/dotfiles/.setup/gitlist
  gitrect;
  # Update our list of git repos
  gitrect -u;
fi 

echo "" # Newline
date;
