#!/usr/bin/env zsh

case "$OSTYPE" in
  darwin*)
    brew update;
    brew upgrade;
    brew cleanup;
  ;;
  linux*)
    sudo pacman -Syu; 
    fd -H -t d -E mod -E vendor '.git$' ~/code/work -x bash -c "cd {//}; git config user.email tyler.m.davis@nordstrom.com; git config http.cookiefile /home/tydavis/.gitcookie-work; " ;
  ;;
esac

fd -H -t d -E mod -E vendor '.git$' ~/ -x bash -c "cd {//}; ~/.bin/fetchgit;" ;
gcloud components update -q;

# Do work updates, then add to our own list
gitrect -d ~/code/work -c ~/code/work/dotfiles/.setup/gitlist
upgit;

echo "" # Newline
date;
