#!/usr/bin/env zsh

# Make sure to always start in $HOME
cd $HOME;

# Always remove the existing file so we let git compare
[ -e ~/.setup/gitlist ] && rm ~/.setup/gitlist
touch ~/.setup/gitlist

gitTmp=$(mktemp /tmp/gitlist.XXXX)

# Iterate through all code folders and produce a CSV of
# folder,remote=URL,remote2=URL
# and so on
for p in $(fd -H -t d '.git$' code); do
  cd $p/..
  y=${p#code/}
  echo -n ${y%.git} >> $gitTmp
  for r in $(git remote); do
    # get remote URL
    echo -n ,$r=$(git config --get remote.$r.url) >> $gitTmp
  done
  echo "" >> $gitTmp
  cd $HOME
done

sort $gitTmp > ~/.setup/gitlist
rm $gitTmp

