#!/usr/bin/env zsh

# contains(string, substring)
#
# Returns 0 if the specified string contains the specified substring,
# otherwise returns 1.
contains() {
    string="$1"
    substring="$2"
    if test "${string#*$substring}" != "$string"
    then
        return 0    # $substring is in $string
    else
        return 1    # $substring is not in $string
    fi
}

# Make sure to always start in $HOME
cd $HOME;

# Always remove the existing file so we let git compare
[ -e ~/.setup/gitlist ] && rm ~/.setup/gitlist
touch ~/.setup/gitlist

gitTmp=$(mktemp /tmp/gitlist.XXXX)

# Iterate through all code folders and produce a CSV of
# folder,remote=URL,remote2=URL
# and so on
for p in $(fd -H --exclude="vendor" -t d '.git$' code); do
  if contains $p ".git"
  then
    cd $p/..
  else
    cd $p
  fi
  y=${p#code/}
  echo -n ${y%.git} >> $gitTmp
  for r in $(git remote); do
    # get remote URL
    echo -n ,$r=$(git config --get remote.$r.url) >> $gitTmp
  done
  echo "" >> $gitTmp
  cd $HOME
done

sort -h $gitTmp > ~/.setup/gitlist
rm $gitTmp


